version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ubu
      POSTGRES_PASSWORD: tootechnical
      POSTGRES_DB: todoapp
    ports: 
    - "5432"
    volumes:
    - "/Users/lfuller/Desktop/cleanup/todoapp/todoapp/forsql:/var/lib/postgresql/new"
  web:
    image: todoapp2
    depends_on:
      - db
    ports:
      - "5000:5000"
